### PR TITLE
Doc improvements

### PR DESCRIPTION
**Pull request by rdaneel-olivaw**
I verified it works, nerves_interim_wifi is able to configure the interface and I can connect.

### CODE REVIEW

**Comment by fhunleth** [comment]
Thanks!

Could you squash the commits together so that there's only one commit? If you're using `git` from the commandline, run `git rebase -i origin/master`, mark the commits to squash together with `s`'s, save, and then force push the update.

**Comment by rdaneel-olivaw** [comment]
I did the squash, but I think I messed up something, sorry. Initially I forked the project, but  I'm not sure that is a prerequisite to a pull request. Maybe you should just reject everything and I should redo it  from scratch, after RTFM.

**Comment by fhunleth** [comment]
It looks like you merged at the end. After the squash, you'll need to force push to update your repository. And, yes, forking the repository is a prerequisite to sending a pull request. Don't worry about the extra tries. It's better to make the extra tries on a simple change like this one than a really complicated one.

**Comment by GregMefford** [comment]
Thanks again for taking the time to submit this improvement! 🚀 👍 
Did you want to take another stab at squashing and force-pushing, or should I just do it on this end?

I think what you'd need to do is something like this, assuming `origin` points to your personal fork:
```
git checkout doc-improvements
git rebase -i origin/master
# (change the beginning of each line except the first one to "s" for "squash")
git push --force origin doc-improvements
```

Happy to help if it doesn't work and you want to keep learning!

**Comment by rdaneel-olivaw** [comment]
Does it look better now? 
Thanks,
-Gug

**Comment by GregMefford** [comment]
Perfect! 💯 ✨ 
Thanks again for your contribution!

**Pull request merged**
